"""Plain-English summary of the facts JSON, generated by an LLM and checked number by number.

The LLM (Claude, via the Anthropic API) sees only the facts JSON (aggregate numbers,
no patient rows) and must answer as findings, each citing the fact IDs it uses.
check_finding() then verifies that every number in a finding's text matches one of its
cited facts. Findings that fail are rejected and listed, never shown as findings.
Needs the [llm] extra (anthropic).
"""

import json
import os
import re
from dataclasses import dataclass, field

MODEL = "claude-opus-5-5"
FALLBACK_BETA = "server-side-fallback-2026-07-01"
MAX_FINDINGS = 8

# Numbers that may appear without a cited fact: the eGFR years and lines (never as a
# percentage), and "95%" for the confidence level.
CONTEXT_NUMBERS = frozenset({2009.0, 2021.0, 60.0, 30.0, 20.0})
CI_LEVEL = 95.0

SYSTEM_PROMPT = """\
You summarise a fairness audit of a clinical risk model for a hospital equity lead who is \
not a statistician. You receive a JSON object of facts computed by the audit software. \
Write 4 to 8 findings, most important first.

Rules:
- Use only numbers that appear in the facts. Do not compute new numbers (no differences, \
ratios or averages of your own).
- Number style: write rates, shares and their gaps as percentages with one decimal \
(0.796 -> 79.6%, a gap of -0.026 -> -2.6 percentage points, a CI of 0.0707 to 0.1813 -> \
7.1 to 18.1 percentage points). Write AUC and observed/expected (O/E) with two decimals \
(0.6434 -> 0.64). Write counts as whole numbers with thousands commas (20,997).
- Every finding lists in fact_ids the IDs of all facts whose numbers it uses.
- Say when a group is flagged small_group: its numbers are uncertain.
- Mention confidence intervals when two groups' intervals overlap.
- Describe gaps; do not call the model "fair", "unfair", "biased" or "safe".
- Anything about eGFR is from synthetic patients: say "synthetic" in that finding.
- Plain words. Explain AUC, false negative rate and calibration the first time you use them."""

OUTPUT_SCHEMA = {
    "type": "object",
    "properties": {
        "findings": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "text": {"type": "string"},
                    "fact_ids": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["text", "fact_ids"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["findings"],
    "additionalProperties": False,
}

# A number: optional sign, digits with optional thousands commas, optional decimals, optional %.
_NUMBER = re.compile(
    r"(?<![\w.])[-+−]?\d{1,3}(?:,\d{3})+(?:\.\d+)?%?|(?<![\w.])[-+−]?\d+(?:\.\d+)?%?"
)


@dataclass(frozen=True)
class Finding:
    text: str
    fact_ids: tuple[str, ...]


@dataclass(frozen=True)
class Rejected:
    text: str
    reason: str
    attempt: int = 1  # which attempt produced it; earlier ones were rewritten


@dataclass
class Summary:
    findings: list[Finding] = field(default_factory=list)
    rejected: list[Rejected] = field(default_factory=list)
    model: str = MODEL
    attempts: int = 0
    error: str | None = None

    @property
    def rejected_final(self) -> list[Rejected]:
        """Rejected in the last attempt: these findings are missing from the summary."""
        return [r for r in self.rejected if r.attempt == self.attempts]

    @property
    def rejected_earlier(self) -> list[Rejected]:
        """Caught in an earlier attempt and sent back to be rewritten."""
        return [r for r in self.rejected if r.attempt < self.attempts]

    def to_dict(self) -> dict:
        return {
            "model": self.model,
            "attempts": self.attempts,
            "error": self.error,
            "findings": [{"text": f.text, "fact_ids": list(f.fact_ids)} for f in self.findings],
            "rejected": [
                {"text": r.text, "reason": r.reason, "attempt": r.attempt} for r in self.rejected
            ],
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Summary":
        return cls(
            findings=[Finding(f["text"], tuple(f["fact_ids"])) for f in data["findings"]],
            rejected=[
                Rejected(r["text"], r["reason"], r.get("attempt", 1)) for r in data["rejected"]
            ],
            model=data["model"],
            attempts=data["attempts"],
            error=data["error"],
        )


# ---------------------------------------------------------------- the guardrail


def extract_numbers(text: str) -> list[tuple[str, float, bool, int]]:
    """Every number in text as (as written, absolute value, is a percentage, decimals)."""
    out = []
    for match in _NUMBER.finditer(text):
        raw = match.group()
        is_pct = raw.endswith("%")
        digits = raw.rstrip("%").lstrip("+-−").replace(",", "")
        decimals = len(digits.split(".")[1]) if "." in digits else 0
        out.append((raw, abs(float(digits)), is_pct, decimals))
    return out


def _fact_numbers(fact: dict) -> list[float]:
    values = [fact.get("value"), fact.get("n")] + list(fact.get("ci_95", []))
    return [abs(float(v)) for v in values if v is not None]


def _matches(number: float, is_pct: bool, decimals: int, value: float) -> bool:
    # A number written with d decimals matches value if value rounds to it. Allow a
    # value written as a percentage (0.796 -> 79.6%), with or without the % sign.
    tolerance = 0.5 * 10**-decimals + 1e-9
    candidates = [value * 100] if is_pct else [value, value * 100]
    return any(abs(number - c) <= tolerance for c in candidates)


def check_finding(text: str, fact_ids, facts: dict) -> str | None:
    """None if the finding is grounded, else the reason it is rejected."""
    if not fact_ids:
        return "cites no facts"
    unknown = [fid for fid in fact_ids if fid not in facts]
    if unknown:
        return f"cites unknown fact id(s) {unknown}"
    cited = [facts[fid] for fid in fact_ids]
    # Numbers inside the cited IDs (age bands like "50-59") may be mentioned too.
    id_numbers = {float(n) for fid in fact_ids for n in re.findall(r"\d+", fid)}
    for raw, number, is_pct, decimals in extract_numbers(text):
        if (number in CONTEXT_NUMBERS and not is_pct) or (number == CI_LEVEL and is_pct):
            continue
        if number in id_numbers and not is_pct:
            continue
        if not any(_matches(number, is_pct, decimals, v) for f in cited for v in _fact_numbers(f)):
            return f"{raw} does not match any cited fact"
    return None


# ---------------------------------------------------------------- calling Claude


def make_client():
    """An Anthropic client if ANTHROPIC_API_KEY is set, else None (no summary)."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None
    import anthropic

    return anthropic.Anthropic()


def _ask(client, messages: list) -> tuple[object, list[dict] | None, str | None]:
    response = client.beta.messages.create(
        model=MODEL,
        max_tokens=16000,
        betas=[FALLBACK_BETA],
        fallbacks="default",
        output_config={
            "effort": "medium",
            "format": {"type": "json_schema", "schema": OUTPUT_SCHEMA},
        },
        system=SYSTEM_PROMPT,
        messages=messages,
    )
    if response.stop_reason == "refusal":
        return response, None, "the model declined to write a summary"
    if response.stop_reason == "max_tokens":
        return response, None, "the summary was cut off (max_tokens)"
    text = next((b.text for b in response.content if b.type == "text"), None)
    try:
        return response, json.loads(text)["findings"], None
    except (TypeError, ValueError, KeyError):
        return response, None, "the model's answer was not valid JSON"


def summarise(facts_json: dict, client, *, retries: int = 1) -> Summary:
    """Ask Claude for findings, keep only those that pass check_finding.

    If any finding fails, Claude gets one more try (by default) with the reasons.
    Summary.rejected keeps the failures of every attempt, tagged with the attempt number:
    rejected_earlier were rewritten, rejected_final are missing from the summary.
    """
    facts = facts_json["facts"]
    messages = [
        {
            "role": "user",
            "content": "Facts from the audit (JSON):\n" + json.dumps(facts_json, indent=1),
        }
    ]
    summary = Summary()
    for attempt in range(retries + 1):
        summary.attempts = attempt + 1
        response, raw, error = _ask(client, messages)
        if error:
            summary.error = error
            return summary
        summary.model = getattr(response, "model", MODEL) or MODEL
        accepted, rejected = [], []
        for item in raw[:MAX_FINDINGS]:
            reason = check_finding(item["text"], item["fact_ids"], facts)
            if reason is None:
                accepted.append(Finding(item["text"], tuple(item["fact_ids"])))
            else:
                rejected.append(Rejected(item["text"], reason, attempt + 1))
        summary.findings = accepted
        summary.rejected += rejected
        if not rejected or attempt == retries:
            return summary
        feedback = "\n".join(f"- {r.text!r}: {r.reason}" for r in rejected)
        messages += [
            {"role": "assistant", "content": response.content},
            {
                "role": "user",
                "content": "These findings failed the number check:\n"
                f"{feedback}\nRewrite all findings using only numbers from the cited facts.",
            },
        ]
    return summary
