"""Build the HTML audit report from outputs/ (UCI audit, plus the eGFR result if present).

Git Bash, from the repo root:
    python scripts/build_report.py            # report without the LLM summary
    python scripts/build_report.py --llm      # also ask Claude for a checked summary
    python scripts/build_report.py --site     # also copy the report to site/index.html
Needs the [report] extra; --llm needs the [llm] extra and ANTHROPIC_API_KEY (in .env).
Run scripts/audit_uci.py (and scripts/egfr_synthea.py) first.

--llm sends aggregate numbers (never patient rows) to the Anthropic API. Groups with 1-10
patients or events are removed first (--min-cell, default 11). The exact payload is saved
to outputs/llm_payload.json and shown before anything is sent. Do not use --llm on real
patient data without your organization's approval.
"""

import argparse
import json
import shutil
from pathlib import Path

import pandas as pd

from equitypanel.report.facts import MIN_CELL, build_facts, suppress_small_cells
from equitypanel.report.html import build_report
from equitypanel.report.summary import Summary, make_client, summarise

ROOT = Path(__file__).resolve().parents[1]

DATA_CREDITS = [
    "Readmission data: Clore J, Cios K, DeShazo J, Strack B (2014). Diabetes 130-US Hospitals "
    "for Years 1999-2008 [Dataset]. UCI Machine Learning Repository. "
    "https://doi.org/10.24432/C5230J. Licensed under CC BY 4.0 "
    "(https://creativecommons.org/licenses/by/4.0/); aggregated and modified by EquityPanel.",
    "Synthetic patients: Synthea sample data (https://github.com/synthetichealth/"
    "synthea-sample-data, no license stated), generated by Synthea (The MITRE Corporation, "
    "Apache 2.0). Walonoski J, et al. JAMIA 2018;25(3):230-238. "
    "https://doi.org/10.1093/jamia/ocx079.",
]
SITE_NOTE = (
    "This page sets no cookies and runs no analytics or scripts. It is hosted on GitHub Pages, "
    "which logs visitor IP addresses under GitHub's privacy statement."
)


def _llm_summary(facts: dict, client, out: Path, args) -> Summary | None:
    """Suppress small cells, show and save the payload, ask, then call the API."""
    if args.allow_small_cells:
        payload, suppressed = facts, []
    else:
        payload, suppressed = suppress_small_cells(facts, args.min_cell)
    payload_path = out / "llm_payload.json"
    payload_path.write_text(json.dumps(payload, indent=1) + "\n", encoding="utf-8")
    n_facts = len(payload["facts"])
    print(f"LLM payload: {n_facts} aggregate facts, no patient rows -> {payload_path}")
    if args.allow_small_cells:
        print("Small-cell suppression is OFF (--allow-small-cells): use only on public data.")
    else:
        hidden = ", ".join(suppressed) or "none"
        print(f"Suppressed (fewer than {args.min_cell} patients or events): {hidden}")
    print("It will be sent to the Anthropic API. Do not send real patient data without approval.")
    if not args.yes and input("Send it? [y/N] ").strip().lower() != "y":
        print("Not sent; building without a summary.")
        return None
    summary = summarise(payload, client)
    if args.allow_small_cells:
        summary.min_cell = None
    return summary


def _read_csv(path: Path) -> pd.DataFrame:
    # Group labels like "<50" must stay strings.
    return pd.read_csv(path, dtype={"group": str})


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--outputs", type=Path, default=ROOT / "outputs")
    parser.add_argument("--llm", action="store_true", help="ask Claude for a checked summary")
    parser.add_argument(
        "--reuse-summary",
        action="store_true",
        help="reuse outputs/uci_summary.json instead of calling the API again",
    )
    parser.add_argument("--site", action="store_true", help="also write site/index.html")
    parser.add_argument(
        "--min-cell",
        type=int,
        default=MIN_CELL,
        help="with --llm: remove groups with fewer than this many patients or events (default 11)",
    )
    parser.add_argument(
        "--allow-small-cells",
        action="store_true",
        help="with --llm: send small groups too (public or synthetic data only)",
    )
    parser.add_argument("--yes", action="store_true", help="with --llm: send without asking")
    parser.add_argument("--n-boot", type=int, default=1000, help="as used in audit_uci.py")
    parser.add_argument("--seed", type=int, default=0, help="as used in audit_uci.py")
    args = parser.parse_args(argv)
    out = args.outputs

    metrics = _read_csv(out / "uci_audit_metrics.csv")
    calibration = _read_csv(out / "uci_audit_calibration.csv")
    model_info = json.loads((out / "uci_model.json").read_text(encoding="utf-8"))
    egfr_path = out / "egfr_summary.csv"
    egfr = _read_csv(egfr_path) if egfr_path.exists() else None

    facts = build_facts(metrics, model_info, egfr)
    (out / "uci_facts.json").write_text(json.dumps(facts, indent=1) + "\n", encoding="utf-8")

    summary = None
    summary_path = out / "uci_summary.json"
    if args.reuse_summary:
        summary = Summary.from_dict(json.loads(summary_path.read_text(encoding="utf-8")))
    elif args.llm:
        from dotenv import load_dotenv

        load_dotenv(ROOT / ".env")
        client = make_client()
        if client is None:
            print("No ANTHROPIC_API_KEY found (set it in .env); building without a summary.")
        else:
            summary = _llm_summary(facts, client, out, args)
        if summary is not None:
            summary_path.write_text(
                json.dumps(summary.to_dict(), indent=1) + "\n", encoding="utf-8"
            )
            print(
                f"summary: {len(summary.findings)} findings kept, "
                f"{len(summary.rejected)} rejected, {summary.attempts} attempt(s)"
                + (f", error: {summary.error}" if summary.error else "")
            )

    html = build_report(
        metrics,
        calibration,
        model_info,
        egfr,
        summary,
        methods={"n_boot": args.n_boot, "seed": args.seed},
        data_credits=DATA_CREDITS if egfr is not None else DATA_CREDITS[:1],
        footer_note=SITE_NOTE if args.site else None,
    )
    report_path = out / "uci_report.html"
    report_path.write_text(html, encoding="utf-8")
    print(f"wrote {report_path} ({len(html) / 1024:.0f} KB)")
    if args.site:
        site = ROOT / "site"
        site.mkdir(exist_ok=True)
        shutil.copyfile(report_path, site / "index.html")
        print(f"copied to {site / 'index.html'}")


if __name__ == "__main__":
    main()
